Repository dora-farm/farm-dora-buyer, pull requests merged in 2025-05, with the labels that each got.

#14 [FDORA-29] feat: jasypt 적용 및 NCP 수정
  src/main/java/com/farmdora/farmdorabuyer/orders/dto/RefundDTO.java
  src/main/java/com/farmdora/farmdorabuyer/orders/dto/ReviewDTO.java
  src/main/java/com/farmdora/farmdorabuyer/orders/repository/SaleFileRepository.java
  src/main/java/com/farmdora/farmdorabuyer/orders/service/NCPObjectStorageService.java
  src/main/java/com/farmdora/farmdorabuyer/orders/service/NcpImageService.java
  src/main/java/com/farmdora/farmdorabuyer/orders/service/RefundService.java
  src/main/java/com/farmdora/farmdorabuyer/orders/service/ReviewService.java
  src/main/resources/application.yml
Labels: feat

#15 [FDORA-19] feat: 배너 사진 목록 조회 API 구현
  src/main/java/com/farmdora/farmdorabuyer/common/response/SuccessMessage.java
  src/main/java/com/farmdora/farmdorabuyer/entity/Popup.java
  src/main/java/com/farmdora/farmdorabuyer/popup/controller/PopupController.java
  src/main/java/com/farmdora/farmdorabuyer/popup/dto/PopupDTO.java
  src/main/java/com/farmdora/farmdorabuyer/popup/repository/PopupRepository.java
  src/main/java/com/farmdora/farmdorabuyer/popup/service/PopupService.java
  src/main/resources/application.yml
  src/test/java/com/farmdora/farmdorabuyer/popup/controller/PopupControllerTest.java
  src/test/java/com/farmdora/farmdorabuyer/popup/repository/PopupRepositoryTest.java
  src/test/java/com/farmdora/farmdorabuyer/popup/service/PopupServiceTest.java
  src/test/resources/application.yml
Labels: feat

#16 [FDORA-158] feat: 시큐리티 적용 및 장바구니 삭제/조회 로직 수정
  build.gradle
  src/main/java/com/farmdora/farmdorabuyer/auth/JwtAuthenticationFilter.java
  src/main/java/com/farmdora/farmdorabuyer/auth/JwtConstants.java
  src/main/java/com/farmdora/farmdorabuyer/auth/JwtUtil.java
  src/main/java/com/farmdora/farmdorabuyer/auth/SecurityConfig.java
  src/main/java/com/farmdora/farmdorabuyer/basket/controller/BasketController.java
  src/main/java/com/farmdora/farmdorabuyer/basket/dto/BasketResponseDto.java
  src/main/java/com/farmdora/farmdorabuyer/basket/service/BasketService.java
  src/main/java/com/farmdora/farmdorabuyer/config/JasyptConfig.java
  src/main/java/com/farmdora/farmdorabuyer/config/RedisConfig.java
  src/main/java/com/farmdora/farmdorabuyer/config/WebConfig.java
  src/main/java/com/farmdora/farmdorabuyer/like/controller/LikeController.java
  src/main/java/com/farmdora/farmdorabuyer/orders/controller/OrderController.java
  src/main/java/com/farmdora/farmdorabuyer/orders/controller/PurchaseController.java
  src/main/java/com/farmdora/farmdorabuyer/orders/controller/RefundController.java
  src/main/java/com/farmdora/farmdorabuyer/orders/controller/ReviewController.java
  src/main/java/com/farmdora/farmdorabuyer/orders/repository/BasketRepository.java
  src/main/java/com/farmdora/farmdorabuyer/orders/service/NCPObjectStorageService.java
  src/main/resources/application.yml
  src/test/java/com/farmdora/farmdorabuyer/ControllerTest.java
  src/test/java/com/farmdora/farmdorabuyer/basket/controller/BasketControllerTest.java
  src/test/java/com/farmdora/farmdorabuyer/basket/service/BasketServiceTest.java
  src/test/java/com/farmdora/farmdorabuyer/like/controller/LikeControllerTest.java
  src/test/java/com/farmdora/farmdorabuyer/orders/controller/PurchaseControllerTest.java
  src/test/java/com/farmdora/farmdorabuyer/orders/service/PurchaseServiceTest.java
  src/test/java/com/farmdora/farmdorabuyer/security/TestSecurityConfig.java
  src/test/java/com/farmdora/farmdorabuyer/security/WithCustomMockUser.java
  src/test/java/com/farmdora/farmdorabuyer/security/WithCustomMockUserSecurityContextFactory.java
  src/test/resources/application.yml
Labels: refactor, fix

#20 [FDORA-162] fix: 테스트 코드 및 설정 수정
  src/main/java/com/farmdora/farmdorabuyer/basket/dto/BasketResponseDto.java
  src/main/java/com/farmdora/farmdorabuyer/orders/repository/BasketRepository.java
  src/test/java/com/farmdora/farmdorabuyer/ControllerTest.java
  src/test/java/com/farmdora/farmdorabuyer/popup/controller/PopupControllerTest.java
  src/test/resources/application.yml
Labels: fix

#21 [FDORA-164] fix: 운영 DB 설정 변경
  src/main/resources/application-prod.yml
Labels: fix

#23 [FDORA-165] feat: 주문 로직 동시성 제어 설정
  src/main/java/com/farmdora/farmdorabuyer/entity/Depot.java
  src/main/java/com/farmdora/farmdorabuyer/entity/Order.java
  src/main/java/com/farmdora/farmdorabuyer/orders/repository/OptionRepository.java
  src/main/java/com/farmdora/farmdorabuyer/orders/service/PurchaseService.java
  src/test/java/com/farmdora/farmdorabuyer/basket/service/BasketServiceTest.java
  src/test/java/com/farmdora/farmdorabuyer/orders/service/PurchaseConcurrencyTest.java
  src/test/java/com/farmdora/farmdorabuyer/orders/service/PurchaseServiceTest.java
Labels: feat

#24 [FDORA-169] feat: 주문 로직에 Pay 데이터 저장 구현
  src/main/java/com/farmdora/farmdorabuyer/entity/User.java
  src/main/java/com/farmdora/farmdorabuyer/orders/repository/BankTypeRepository.java
  src/main/java/com/farmdora/farmdorabuyer/orders/repository/PayStatusRepository.java
  src/main/java/com/farmdora/farmdorabuyer/orders/repository/UserRepository.java
  src/main/java/com/farmdora/farmdorabuyer/orders/service/PurchaseService.java
  src/test/java/com/farmdora/farmdorabuyer/orders/service/PurchaseConcurrencyTest.java
  src/test/java/com/farmdora/farmdorabuyer/orders/service/PurchaseServiceTest.java
Labels: feat

#27 feat: 문의 등록 API 구현
  src/main/java/com/farmdora/farmdorabuyer/question/controller/QuestionController.java
  src/main/java/com/farmdora/farmdorabuyer/question/dto/QuestionRequestDTO.java
  src/main/java/com/farmdora/farmdorabuyer/question/repository/QuestionRepository.java
  src/main/java/com/farmdora/farmdorabuyer/question/service/QuestionService.java
Labels: feat
